name: ci-wf
on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome Step
        run: echo "Welcome TO the Linting Job"
      - name: Clone Repo
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Development Dependencies
        run: npm install
      - name: Lint HTML and CSS Files
        run: |
          npx htmlhint "**/*.html"
          npx stylelint "**/*.css"
  build-website-job:
    runs-on: ubuntu-latest
    needs: lint-job
    steps:
      - name: Welcome to Build Job
        run: echo "Welcome to Build Job"
      - name: Clone Repo
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dev Dependencies
        run: npm install
      - name: Build Website with Parcel
        run: npx parcel build "./src/index.html" --dist-dir "./dist" --public-url "./" --no-cache
  build-image-job:
    runs-on: ubuntu-latest
    needs: build-website-job
    steps:
      - name: Welcome To the Image Building Job
        run: echo "Image Building Job Starting"
      - name: Clone The Repo
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Website Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/w14g2:latest .
      - name: Push Image on Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/w14g2:latest
      - name: List Images
        run: docker image ls
      - name: Run Container
        run: docker run -d -p 2222:80 ${{ secrets.DOCKERHUB_USERNAME }}/w14g2:latest
      - name: List Running Containers
        run: docker container ls
      # - name: Stop The Running Containers
      #   run: docker container stop $(docker container ls)
      # - name: Kill all the unsed resoruces at Runner
      #   run: docker system prune -a --volumes